[toc]

### 异常

#### 异常体系介绍

```mermaid
graph TD;
	Exception --> RuntimeException
	Exception --> 其他异常
```

```markdown
异常是什么？
	程序中可能出现的问题
异常体系的最上层父类是谁？异常分为几类？
	父类：Exception
	异常分为两类：编译时异常、运行时异常
编译时异常和运行时异常的区别？
	编译时异常：
		没有继承RuntimeExcpetion的异常，直接继承于Excpetion
		编译阶段就会错误提示
	运行时异常：
		RuntimeException本身和子类
		编译阶段没有错误提示，运行时出现
```

#### 编译时异常和运行时异常

```markdown
Java文件 -----> 字节码文件
		Javac命令
编译时异常：
	编译阶段就要进行处理的异常，作用在于提醒程序员（如：日期解析异常)

字节码文件 -----> 运行结果
		Java命令
运行时异常：
	RuntimeException及其子类，编译阶段不需要处理。代码运行时出现的异常（如：数组索引越界异常）
	一般是由于参数传递错误带来的问题
```

#### 异常的作用 

##### 作用一

```markdown
错误信息传递：
	异常机制允许我们在出现错误时将错误信息传递给程序的调用者或其他部分。当异常发生时，可以通过抛出异常对象来传递错误信息，并通过异常的类型进行分类。这使得代码可以在不同的层级之间传递错误信息，从而实现更好的错误处理和调试。
```

##### 作用二

```markdown
异常处理：
    Java的异常机制提供了一种结构化的方式来处理程序中的错误情况。通过捕获和处理异常，我们可以在程序出现异常时采取适当的措施，使程序能够优雅地处理异常情况而不会终止执行。异常处理可以使用try-catch块来捕获异常并执行相应的处理逻辑，或者可以将异常继续抛出给上层调用者处理。
    
    异常作用二：异常可以作为方法内部的一种特殊返回值，以便通知调用者底层的执行情况
```

#### 异常的处理方式

##### JVM默认的处理方式

1.把异常的名称，异常原因及异常出现的位置等信息输出在了控制台
2.程序停止执行，异常下面的代码不会再执行了

##### try-catch捕获异常

```java
//格式：
try{
	可能出现异常的代码;
} catch (异常类名 变量名) {
	异常的处理代码;
}
//目的 
//当代码出现异常时，可以让出现继续往下执行

int[] arr = {1,2,3,4,5,6};

try{
	System.out.println(arr[10]);
    //此处出现了异常，程序就会在这里创建一个ArrayIndexOutofBoundsException对象
	//new ArrayIndexoutofBoundsException();
	//使用这个对象到catch的小括号中对比，看括号中的变量是否可以接收这个对象
	//如果能被接收，就表示该异常就被捕获（抓住），执行catch里面对应的代码
	//当catch里面所有的代码执行完毕，继续执行try.,.catch体系下面的其他代码
}catch(ArrayIndexOutofBoundsException e){
	//如果出现了ArrayIndexOutofBoundsException异常，我该如何处理
	System.out.printiIn("索引越界了")；
}
System.out.printin("程序继续执行")；
```

###### try-catch捕获异常的四个问题

```markdown
1.如果try中没有遇到问题，不会执行？
	会把try里面所有的代码全部执行完毕，不会执行catch里面的代码
	注意：只有当出现了异常才会执行catch里面的代码
2.如果try中可能会遇到多个问题，怎么执行？
	会写多个catch与之对应
	细节：如果要捕获多个异常，这些异常中如果存在父子关系，那么父类一定要写在下面
	了解：
		在JDK7之后，可以在catch中同时捕获多个异常，中间用 | 进行隔开
		表示如果出现了A异常或者B异常的话，采取同一种处理方案
3.如果try中遇到的问题没有被捕获，怎么执行？
	try...catch不会执行，当前异常会交给虚拟机处理
4.如果try中遇到了问题，那么try下面的其他代码还会执行吗？
	下面的代码就不会执行了，直接跳转到对应的catch当中，执行catch里面的语句体
	但是如果没有对应catch与之匹配，那么还是会交给虚拟机进行处理
```

```java
//2.如果try中可能会遇到多个问题，怎么执行？
int[]arr={1,2,3,4,5,6};
try{
	System.out.println(arr[10]);//ArrayIndexoutofBoundsException
	System.out.println(2/0);//ArithmeticException
}catch(ArrayIndexOutofBoundsException e){
	System.out.printin("索引越界了")；
}catch(ArithmeticException e){
	System.out.println("除数不能为")；
}catch (Exception e){
	System.out.println("Exception");
}
```

##### 抛出异常

###### throws

注意：写在方法定义处，表示声明一个异常，告诉调用者，使用本方法可能会有哪些异常

```java
public void 方法() throws 异常类名1, 异常类名2...{}

//编译时异常，必须要写
//运行时异常，可以不写
```

###### throw

注意：写在方法内，结束方法，手动抛出异常对象，交给调用者，方法中下面的代码不再执行

```java
public void 方法(){
    throw new NullPointerException();
}
```

```java
public static void main(String[] args) {    
	int[] arr = null;
    int max = 0;
    try{
        max getMax(arr);
    }catch (NullPointerException e){
        System.out.printin("空指针异常")；
    }catch (ArrayIndexoutofBoundsException e){
        System.out.println("索引越界异常")；
    }
    System.out.println(max);
}

public static int getMax(int[] arr)/*throws NullPointerException*/{
	if(arr == null){
        //手动创建一个异常对象，并把这个异常交给方法的调用者处理
        //此时方法就会结束，下面的代码不会再执行了
        throw new NullPointerException();
    }
    if(arr.length == 0){
        //手动创建一个异常对象，并把这个异常交给方法的调用者处理
        //此时方法就会结束，下面的代码不会再执行了
        throw new ArrayIndexoutofBoundsException();
    }
    System.out.println("看看我执行了吗？")；
    int max = arr[0];
    for (int i = 1; i<arr.length; i++){
        if(arr[i] > max){
            max = arr[i];
        }
    }
}
```

###### 总结

```markdown
1.虚拟机默认处理异常的方式
	把异常信息以红色字体打印在控制台，并结束程序
2.捕获：try..catch
	一般用在调用处，能让代码继续往下运行。
3.抛出：throw throws
    在方法中，出现异常了。
    方法就没有继续运行下去的意义了，采取抛出处理。
    让该方法结束运行并告诉调用者出现了问题。
```

#### 异常中的常见方法

##### Throwable的成员方法

| 方法名称                      | 说明                            |
| ----------------------------- | ------------------------------- |
| public String getMessage()    | 返回此throwable的详细消息字符串 |
| public String toString()      | 返回此可抛出的简短描述          |
| public void printStackTrace() | 把异常的错误信息输出在控制台    |

```java
int[] arr = {1, 2, 3, 4, 5, 6};

try {
    System.out.println(arr[10]);
} catch (ArrayIndexOutOfBoundsException e) {
    String message = e.getMessage();
    System.out.println(message);
    //Index 10 out of bounds for length 6

    String str = e.toString();
    System.out.println(str);
    //java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 6

    //在底层是利用System.err.println进行输出
	//把异常的错误信息以红色字体输出在控制台
    //细节：仅仅是打印信息，不会停止程序运行
    e.printStackTrace();
}

System.out.println("语句是否执行");
```

#### 自定义异常

1. 定义异常类
2. 写继承关系
3. 空参构造
4. 带参构造

意义：















